<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<!-- Global packages (private, build-time packages for all projects) -->
	<ItemGroup>
		<GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.7.115" />
	</ItemGroup>
</Project>
