<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ContentTargetFolders>content</ContentTargetFolders>
		<IsPackable>false</IsPackable>
		<NoWarn>$(NoWarn),NU1902</NoWarn>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Web.Website" VersionOverride="[13.0.0, 14)" />
		<PackageReference Include="Umbraco.Cms.Web.BackOffice" VersionOverride="[13.0.0, 14)" />
	</ItemGroup>
	
	<ItemGroup>
		<Content Include="content\App_Plugins\**\*.*">
			<PackagePath>content\App_Plugins</PackagePath>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
		<None Include="build\**\*.*">
			<Pack>True</Pack>
			<PackagePath>buildTransitive</PackagePath>
		</None>
	</ItemGroup>
</Project>
