name: Publish

on:
  release:
    types: [published]

env:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    name: Build
    uses: umbraco/UI-Examples/.github/workflows/build.yml@master
    
  publish:
    name: Publish
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: Get Umbraco package file name
        id: get_package
        run: echo "::set-output name=PACKAGE::$(Get-Item *.zip | Select-Object -First 1 -ExpandProperty Name)"
      
      - name: Setup UmbPack
        if: steps.get_package.outputs.PACKAGE
        run: dotnet tool install --tool-path . Umbraco.Tools.Packages

      - name: Push to Our.Umbraco
        if: steps.get_package.outputs.PACKAGE
        run: ./umbpack push ${{ steps.get_package.outputs.PACKAGE }} -k ${{ secrets.OURUMBRACO_API_KEY }} -a *

      - name: Push to NuGet
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate